CREATE DATABASE IF NOT EXISTS BD_VEICULOS;
USE BD_VEICULOS;

CREATE TABLE IF NOT EXISTS VEICULOS(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
PLACA VARCHAR(10) NOT NULL UNIQUE,
MARCA VARCHAR(50) NOT NULL,
MODELO VARCHAR(50) NOT NULL,
COR VARCHAR(30) NOT NULL,
ANO INT NOT NULL,
PORTE VARCHAR(20) NOT NULL,
TIPOCARGA VARCHAR(30) NOT NULL,
CHASSIS VARCHAR(17) NOT NULL UNIQUE
);